### PR TITLE
Properly Working 

### PR DESCRIPTION
**Pull request by KevinPacunayen**
Body Request:

{
    "username": "kevs",
    "password": "password12"
}

### CODE REVIEW

**Review by marlonmendoza03 — APPROVED** [review]
Well done!

**Review by miguelrefuerzo — APPROVED** [review]
GJ! One step closer para matapos yung project

**Review by marlonmendoza03 — CHANGES_REQUESTED** [review]
#6 Services/LoginCommands/Login.cs

`try
            {
            var user = await _productRepositoryQueries.GetUserWithUsernameAndPassword(userDTO.username.ToLower(), userDTO.password);
            if (user != null || user.isActive == true)
            {
                if (user.username.ToLower() == userDTO.username.ToLower() && user.password == user.password)
                {
                    loginResponse = await MapLoginResponse(userDTO);
                }
            }`

Kindly change the name of _productRepositoryQueries

**Review by marlonmendoza03 — APPROVED** [review]
Perfect!

**Pull request merged**
